external:
  api:
    base-url: ${EXTERNAL_API_BASEURL:http://apis.data.go.kr/B554287/NationalWelfareInformationsV001}
    service-key: ${SERVICE_KEY:}

spring:
  application:
    name: hackathon_v2
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.user.hackathon_v2: INFO